### PR TITLE
Fix #207 (repo branch master -> main)

### LINKED ISSUE #207: Pipeline In org-formation-build.yml Looking For 'master' Branch But CodeCommit Default Now 'main'
### Subject of the issue
When running init-pipeline, the pipeline that is created is looking for the 'master' branch but a recent CodeCommit change creates a repo with the 'main' branch instead.

### Your environment
* version of org-foramtion (ofn --version)
0.9.14
* version of node (node --version)
v14.16.0
* which OS/distro
WSL2 Ubuntu

### Steps to reproduce
org-formation init-pipeline organization.yml --region eu-west-2

### Expected behaviour
pipeline should be triggered by main now that the defaults have changed

### Actual behaviour
pipeline not triggered

It is easy enough to add a new 'master' branch to get round this. Thanks.

### PR DESCRIPTION
**Pull request by stewartcampbell**
*  Fixes https://github.com/org-formation/org-formation-cli/issues/207
* minor cfn-lint fixes
* Trigger pipeline using CloudWatch Event instead of CodePipeline polling

### CODE REVIEW

**Comment by OlafConijn** [comment]
> This fixes #207
> 
> Also added minor cfn-lint fixes.

thanks so much!

**Comment by OlafConijn** [comment]
looks good, i'll do a full test on this later today and merge later today

**Comment by stewartcampbell** [comment]
Great, thanks. I have another PR incoming to trigger the pipeline with a CloudWatch event instead of CodePipeline polling. Just testing now... shouldn't be long.

**Comment by stewartcampbell** [comment]
I have updated this PR instead of adding a new one as they would have conflicted due to main/master. Hopefully that is ok.

**Review by OlafConijn — APPROVED** [review]

**Pull request merged**
