### PR TITLE
[Resolves #152] Get file contents from remote location

### LINKED ISSUE #152: feature: reference template files with a URI
We typically like to keep our cloudformation templates in a separate github repository so we can version them separately from our CI files.   We also deploy our CFN templates to an S3 bucket which gives us a central repository of versioned cloudformation templates that we can reference using a S3 or https URI.  It looks like org-formation expects all file references to be relative to the task file and in the local directory.  Instead of referencing the files in the local directory it would be great if we could reference them directly using a S3 bucket or github URI.

for example instead of `Template: ./password-policy.yaml` I would like to reference my templates :

* `Template: s3://my-repository-bucket/cfn-templates/v1.0.0/password-policy.yaml`
* `Template: https://raw.githubusercontent.com/zaro0508/cfn-templates/v1.0.0/password-policy.yaml`

or maybe the [`!ReadFile`](https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#readfile) function can be expanded to include URI references?

* `Template: !ReadFile s3://my-repository-bucket/cfn-templates/v1.0.0/password-policy.yaml`
* `Template: !ReadFile https://raw.githubusercontent.com/zaro0508/cfn-templates/v1.0.0/password-policy.yaml`

### PR DESCRIPTION
**Pull request by zaro0508**
Add the ability to get file contents from a remote location

### CODE REVIEW

**Comment by zaro0508** [comment]
!ReadFile over https provides marginal value now that update-stacks supports remote files. Also remote file resolving can be done with the !Cmd function (PR #185).

**Comment by zaro0508** [comment]
@OlafConijn I see where remote `!ReadFile` reference would come in handy now.  Take a look at https://github.com/org-formation/org-formation-reference/blob/master/src/templates/010-scps/deny-root-access.yml#L13

I'm setting up something like that now and I want to share those scp policies across my multiple ofn repos.  how would i do it without remote `!ReadFile` support?

**Comment by OlafConijn** [comment]
hi @zaro0508, i think in this case there is a quite a bit of value having `./resources/deny-root-access-policy.json` stored, versioned and deployed alongside the template. 
- moving the policy.json to some other place would make it difficult to understand which version of the policy was deployed by which which version of the template if i would be auditing the history. 
- it is also difficult to control the software-development-life-cycle on stuff that is external to your source code versioning system.

what we are planning to do over at [aws-resource-providers](https://github.com/org-formation/aws-resource-providers) is allow the policy to be part of the resource as an object (as opposed to a string).

**Comment by zaro0508** [comment]
> hi @zaro0508, i think in this case there is a quite a bit of value having `./resources/deny-root-access-policy.json` stored, versioned and deployed alongside the template.

I do plan to keep them together, both would live in our dependent templates repo.  I planned to put both `deploy-root-access.yml` and `deploy-root-access-policy.json` in the remote repo while keeping  `_tasks.yml` in my main repo where ofn does the deployment.  

> * moving the policy.json to some other place would make it difficult to understand which version of the policy was deployed by which which version of the template if i would be auditing the history.
> * it is also difficult to control the software-development-life-cycle on stuff that is external to your source code versioning system.

Don't we do this already with our apps.  I mean ofn depends on a bunch of remote repos (libraries and whatnot) and that doesn't seem to hinder the SDLC for it.  I do plan to pin to specific tags/versions of SCP policies and templates.  I agree that it would be more difficult to get a complete picture since files are remote but I think the benefit of being able to share files outweights the cost of complexity. 

> what we are planning to do over at [aws-resource-providers](https://github.com/org-formation/aws-resource-providers) is allow the policy to be part of the resource as an object (as opposed to a string).

I'm not sure what this would look like, is there an issue with a better description of this?

**Pull request closed without merging**
