### PR TITLE
Support credential process and SSO from AWS CLI config

### PR DESCRIPTION
**Pull request by eduardomourar**
This will add support for credential process and AWS SSO within the AWS CLI config file as well as simplify the profile with MFA. ~~By leveraging a tool like [aws-sso-util](https://github.com/benkehoe/aws-sso-util), users can set AWS SSO even though the AWS SDK does not support it yet.~~ We are using a NPM library to load the AWS SSO configuration now.

Related to #123

### CODE REVIEW

**Comment by OlafConijn** [comment]
nice, thanks so much! we might want to keep an eye on this (https://github.com/org-formation/org-formation-cli/issues/191) too? tx

**Comment by eduardomourar** [comment]
I don't know how to solve the unit testing failing for default profile. We don't m have any AWS_ env variable set, right?

**Comment by zaro0508** [comment]
Is there some documentation we can add for this?

**Comment by OlafConijn** [comment]
> Is there some documentation we can add for this?

i think after this is done it should start to behave more like people expect :)

**Comment by OlafConijn** [comment]
> I don't know how to solve the unit testing failing for default profile. We don't m have any AWS_ env variable set, right?

No we dont have any env var set. 

I believe that from the `CredentialProviderChain.defaultProviders` the `SharedIniFileCredentials` provider returns the credentials. I don't believe this handler uses the environment variables you set in the beforeAll. might be a difference between CLI and SDK? there is more than a few....

**Comment by OlafConijn** [comment]
i think this is great. thanks!

**Review by OlafConijn — APPROVED** [review]

**Comment by eduardomourar** [comment]
Feel free to merge whenever you want

**Comment by OlafConijn** [comment]
does this PR close #191?

**Comment by eduardomourar** [comment]
> does this PR close #191?

Probably not. We should ask the user for feedback.

**Pull request merged**
