### PR TITLE
add info about Billing Alerts

### PR DESCRIPTION
**Pull request by hffmnn**
I guess without the configuration in the root account the example does not work.

### CODE REVIEW

**Review by zaro0508 — APPROVED** [review]

**Comment by hffmnn** [comment]
Hm, seems like this is not the only problem. The root account has billing alerts enabled, but still we get this when trying to deploy:

```
Resource Budget failed because Account 123123123 is a linked account. To enable budgets for your account, ask the payer account to enable budgets first.
```

**Comment by OlafConijn** [comment]
i believe IAM access to billing must be enabled (not sure whether you need both? 🤔 ): https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/control-access-billing.html#ControllingAccessWebsite-Activate

**Comment by hffmnn** [comment]
The account I want to deploy with has access to billing. And I also added a dummy budget... not sure why this does not work.

**Comment by eduardomourar** [comment]
We ran into the same issue last week and we had to wait 24 hours after an account was created to do this. I believe we also enabled the IAM permission to billing.

**Comment by hffmnn** [comment]
@eduardomourar Thanks for that hint.

We enabled the option to receive Billing Alerts and the IAM roles today. So I will retry a deployment tomorrow and update this PR accordingly.

**Comment by hffmnn** [comment]
The deployment works now. Tried after ~17 hours. We enabled both in our Root Account, so I can not say what is needed and what is not. I update the PR accordingly.

**Comment by OlafConijn** [comment]
great, thanks! @eduardomourar -> having learned this it probably makes sense to increase the failure tolerance on the reference archicecture.  and add a note.

@hffmnn , feel free to merge! thanks so much

**Comment by hffmnn** [comment]
> feel free to merge! thanks so much

@OlafConijn always a pleasure to help to make a great project even better. But: I can't merge. Not sure who to mention here.

**Comment by OlafConijn** [comment]
misread your comment... would you like to join the project as collaborator? very happy to add you

**Comment by OlafConijn** [comment]
invite sent, also feel free to join our slack: https://join.slack.com/t/org-formation/shared_invite/enQtOTA5NjM3Mzc4ODUwLTMxZjYxYzljZTE5YWUzODE2MTNmYjM5NTY5Nzc3MzljNjVlZGQ1ODEzZDgyMWVkMDg3Mzk1ZjQ1ZjM4MDhlOGM

**Comment by hffmnn** [comment]
Nice. Thank you very much. Will join.

**Pull request merged**
